services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API: "https://snappishly-impressive-klipspringer.cloudpub.ru"
    restart: always